title: Geronimo Trumpfheller - Cybersecurity Portfolio
description: "Passionate about defending digital landscapes. I specialize in threat intelligence, malware analysis, and building secure systems."
author: Geronimo Trumpfheller
baseurl: ""
repository: "iammo31/iammo31.github.io"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  
exclude:
  - "*.bak"